### ISSUE TITLE
Remove bin folder

### ISSUE THREAD

**Issue by theKidOfArcrania** [andy98725/Base-Wars-3#2]
Please remove the bin folder (and set it as a .gitignore file)

Typically, you should not add files to git that correspond to "generated" binary files, as these can potentially change with little regards to actual changes you made to source files. 

Instead you should create explicit instructions of building the source files.

You know, I compiled your files using: javac version 1.8.0_191, and I ended up with almost every single class file as diff'd, even as I only made a small change!

**Comment by andy98725** [comment]
Will do, thanks. Added to gitignore.
